CREATE TABLE geocode_collection (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  map_table varchar(255) NOT NULL,
  map_coords_id int(11) NOT NULL,
  language varchar(255) DEFAULT NULL,
  created int(11) NOT NULL,
  modified int(11) NOT NULL,
  json_data text NOT NULL,
  formatted_address text DEFAULT NULL,
  street_address text DEFAULT NULL,
  route text DEFAULT NULL,
  intersection text DEFAULT NULL,
  political text DEFAULT NULL,
  country varchar(255) DEFAULT NULL,
  administrative_area_level_1 varchar(255) DEFAULT NULL,
  administrative_area_level_2 varchar(255) DEFAULT NULL,
  administrative_area_level_3 text DEFAULT NULL,
  administrative_area_level_4 text DEFAULT NULL,
  administrative_area_level_5 text DEFAULT NULL,
  colloquial_area text DEFAULT NULL,
  locality varchar(255) DEFAULT NULL,
  ward text DEFAULT NULL,
  sublocality text DEFAULT NULL,
  neighborhood text DEFAULT NULL,
  premise text DEFAULT NULL,
  subpremise text DEFAULT NULL,
  postal_code varchar(255) DEFAULT NULL,
  natural_feature text DEFAULT NULL,
  airport text DEFAULT NULL,
  park text DEFAULT NULL,
  point_of_interest text DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX IDX_en_geocode_collection_administrative_area_level_1 (administrative_area_level_1),
  INDEX IDX_en_geocode_collection_administrative_area_level_2 (administrative_area_level_2),
  INDEX IDX_en_geocode_collection_country (country),
  INDEX IDX_en_geocode_collection_language (language),
  INDEX IDX_en_geocode_collection_locality (locality),
  INDEX IDX_en_geocode_collection_map_table (map_table, map_coords_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;