import Consts from 'src/settings/Consts';


export default {
    'countries/undefined/name': 'Other places',
    'errors/new_point/photos_upload': 'Please attach at least one photo.',
    'errors/new_point/photos_uploaded_yet': 'Photos are still being downloaded.',
    'errors/new_point/photos_upload_more_than_available': 'The number of photos is more than acceptable. Quantity exceeded on:',
    'errors/new_point/coords_empty': 'Please select a location on the map.',
    'errors/new_point/another_actions': 'First, finish adding the new placemark.',
    'errors/link_id_not_found': 'Placemark with the same id is not found in this map, maybe it has been removed :(',
    'errors/search/empty_params': 'Please, enter search data.',
    'errors/new_point/wrong_email': 'Incorrect email',
    'errors/update_point/wrong_password': 'The password is entered incorrectly, or this isn\'t your entry.',
    'errors/update_point/empty_password': 'You need to enter the password that was previously sent to you by email.',
    'text/new_point/loading': 'loading...',
    'errors/system': 'System error! Please contact site administrator.',
    'success/new_point/placemark_added': 'Mark added, now you go into the edit section',
    'success/new_point/created': 'The record was successfully added',
    'success/new_point/updated': 'The record updated successfully',
    'success/new_article/created': 'New article was successfullt created',
    'success/article/updated': 'The article was successfullt updated',
    'success/article/deleted': 'The article was successfullt deleted',
    'success/point/deleted': 'The record was successfully deleted',
    'visitors/welcome/1/text': 'Thank You for visiting our website! <br>I hope You enjoy your stay :).',
    'visitors/interest/1/title/text': `<span style="color:#0070C3">Thank You for your interest!</span>`,
    'visitors/interest/1/description/text': "If You don't mind, we will occasionally send You emails with new interesting sites. <br><br> <small>If You wish to unsubscribe from our emails, you can always click the letter button <b style=\"font-weight:bold;\">I'm not interested</b></small>.",
    'buttons/new_point/add': 'Add',
    'buttons/new_point/delete_photo': 'Delete',
    'buttons/new_point/delete_placemark': 'Delete placemark',
    'buttons/new_point/update': 'Edit',
    'buttons/new_point/existing_photos_title': 'Uploaded photos',
    'sweet_alert/delete_placemark/notation': 'The data will be permanently deleted',
    'buttons/new_point/close': 'Cancel',
    'sweet_alert/are_you_sure': 'Are you sure?',
    'sweet_alert/new_point/close/notation': 'Your data will not be saved.',
    'sweet_alert/redact_point/close/notation': 'Are you want to cancel editing?',
    'sweet_alert/yes': 'Yes',
    'sweet_alert/no': 'No',
    'buttons/placemark/viewer/hide': 'On map',
    'buttons/placemark/viewer/show': 'Back',
    'buttons/placemark/viewer/close': 'Close',
    'buttons/new_point/place_at_map': 'Change the location on the map',
    'buttons/new_point/return_to_editor': 'Return to edition',
    'buttons/new_point/cancel': 'Cancel',
    'buttons/new_point/commit': 'Save',
    'warning/search/empty_result': 'Nothing found.',
    'notice/new_point/check_place': 'Specify the location on the map',
    'notice/load_placemarks/big_zoom': 'Nothing is loaded. Too much area. Try to bring the scale.',
    'notice/map/filter/start/text': 'Is filtering, please wait.',
    'notice/map/filter/reset/text': 'There is a filter reset, please wait.',
    'text/new_point/title': 'Add placemark to the map',
    'text/new_point/title_update': 'Update record',
    'text/general_review': 'General review',
    'map/panel_tools/where_am_i/title': '<br>where am I',
    'map/panel_tools/placemark_add_open/title': 'add a<br>new placemark',
    'map/panel_tools/link/catalog': 'Catalog',
    'map/panel_tools/link/main': 'Home page',
    'map/placemark/link_to_catalog': 'Look in the catalog',
    'map/panel_tools/filter/category/title': 'Show only:',
    'map/panel_tools/filter/category/selected/title': 'Selected:',
    'map/panel_tools/filter/title': '<br>filter',
    'panel_tools/settings/title': 'Settings',
    'panel_tools/settings_back/title': 'Back',
    'panel_tools/settings/head': 'Settings',
    'panel_tools/settings/language/title': 'Sile language',
    'map/panel_tools/filter/head': 'Filter',
    'catalog/panel_tools/link/map': 'Map',
    'map/panel_tools/filter_back/title': '<br>back',
    'map/panel_tools/filter_reset/title': '<br>reset filter',
    'catalog/panel_tools/link/filter': 'Search',
    'catalog/panel_tools/link/catalog': 'Catalog',
    'catalog/panel_tools/link/catalog/search': 'Search',
    'catalog/panel_tools/link/article': 'Articles',
    'breadcrumbs/catalog/text': 'Catalog',
    'breadcrumbs/article/text': 'Articles',
    'map/panel_tools/link/all_placemarks': 'All placemarks',
    'map/panel_tools/link/filter': 'Search',
    'text/new_point/step_1': 'Description.',
    'form/map_generic_new_point/email/label': 'Your  Email (optional). This will give you the ability to edit that record in the future.',
    'form/map_generic_new_point/password/label': 'Enter the password (it was previously sent to you by email if you provided an email).',
    'map/placemark/link/text': 'The link to the place: ',
    'catalog/placemark/link_to_map/text': 'See on map ',
    'map/placemark/adress/text': '', //Адрес места:
    'email/send_password_after_create_placemark/subject': 'Your password',
    'email/send_password_after_create_placemark/body': 'Password: <b>%password%</b><br>With this password you will be able to edit entries on any of the cards project Mapstore.',
    'email/send_password_after_create_placemark/alt_body': 'With this password you will be able to edit entries on any of the cards project Mapstore.',
    'catalog/index/header': 'Select a country',
    'catalog/country/back_link': 'Back to countries selection',
    'catalog/placemark/back_link_states': 'Other placemarks in this region',
    'catalog/placemark/back_link_countries': 'Other placemarks in this country',
    'catalog/placemark/back_link_undefined': 'Other placemarks',
    'catalog/country/photoalbum_title/text': 'Uploaded latest photos',
    'catalog/state/photoalbum_title/text': 'Uploaded latest photos',
    'catalog/state/back_link_states': 'Select another region',
    'catalog/state/back_link_countries': 'Other countries',
    'relevant_placemarks/title/text': 'It will be interesting for you:',
    'another_placemarks/title/text': 'Another placemarks:',
    'another_articles/title/text': 'Another articles:',
    'placemarks_count/1/text': 'The number of placemarks: ',
    'placemarks_count/2/text': 'placemarks: ',
    'catalog/states/regions/list/title': 'Regions',
    'sitemap_categories/header/text': 'Select a category',
    'sitemap/empty_list/text': 'The list is empty',
    'sitemap_countries/header/text': 'Select a country',
    'upload_file_plugin/uploadstr/value': '',
    'upload_file_plugin/deletelStr/value': 'Cancel',
    'page_bottom/sitemap_countries/text': 'Sitemap for placemarks by country selection',
    'page_bottom/sitemap_categories/text': 'Sitemap for placemarks by category selection',
    'page_bottom/articles_countries/text': 'Articles by country selection',
    'page_bottom/articles_categories/text': 'Articles by category selection',
    'articles_countries/header/text': 'Choose a country',
    'articles_categories/header/text': 'Choose a category',
    'site/title/catalog/sitemap_countries/country': 'Site map. %country%.',
    'site/title/catalog/sitemap_countries/index': 'Site map. Countries.',
    'site/title/catalog/sitemap_categories/category': 'Site map. %category%.',
    'site/title/catalog/sitemap_categories/index': 'Site map. Categories.',
    'site/keywords/catalog/sitemap_countries/index': 'countries',
    'site/keywords/catalog/sitemap_categories/index': 'categories',
    'text_form/tags/a/title': 'Link',
    'text_form/tags/p/title': 'Paragraph',
    'text_form/tags/b/title': 'Bold',
    'text_form/tags/strong/title': 'Tag <strong>',
    'text_form/tags/img/title': 'Image',
    'site/title/articles/country': 'Articles abount world landmarks. %country%.',
    'site/title/articles/category': 'Articles abount world landmarks. %category%.',
    'site/title/articles/index': 'Articles abount world landmarks',
    'site/description/articles/country': '',
    'site/description/articles/category': '',
    'site/description/articles/index': '',
    'site/keywords/articles/index': '',
    ['form/map_new_point/category/' + Consts.MY_NONE_CATEGORY_CODE]: 'Select from the list',
    'form/map_new_point/category/0': 'Other places',
    'form/map_new_point/category/1': 'Castles',
    'form/map_new_point/category/2': 'Palaces, manor houses',
    'form/map_new_point/category/3': 'Abandoned buildings',
    'form/map_new_point/category/4': 'Monuments of architecture, historic buildings',
    'form/map_new_point/category/5': 'Architectural complexes (kremlins, monasteries)',
    'form/map_new_point/category/6': 'Temples, churches (Christianity)',
    'form/map_new_point/category/7': 'Mosques',
    'form/map_new_point/category/8': 'Synagogues',
    'form/map_new_point/category/9': 'Museums, exhibition halls',
    'form/map_new_point/category/10': 'Memorials and monuments',
    'form/map_new_point/category/11': 'Places of culture (theatres, conservatories)',
    'form/map_new_point/category/12': 'Zoos, dolphinariums',
    'form/map_new_point/category/13': 'Circuses',
    'form/map_new_point/category/14': 'Industrial buildings',
    'form/map_new_point/category/15': 'Gardens and parks',
    'form/map_new_point/category/16': 'Memorial places',
    'form/map_new_point/category/17': 'Unusual places',
    'form/map_new_point/category/18': 'Mountains',
    'form/map_new_point/category/19': 'Volcanoes',
    'form/map_new_point/category/20': 'Caves',
    'form/map_new_point/category/21': 'Ponds',
    'form/map_new_point/category/22': 'Waterfalls',
    'form/map_new_point/category/23': 'Springs',
    'form/map_new_point/category/24': 'Archaeological sites, ruins',
    'form/map_new_point/category/25': 'Fountains',
    'form/map_new_point/category/26': 'Fortresses, fortifications',
    'form/map_new_point/category/27': 'Streets, squares, boulevards',
    'form/map_new_point/category/28': 'Buddhist temples',
    'form/map_new_point/category/29': 'Educational institutions',
    'form/map_new_point/category/30': 'Libraries',
    'form/map_new_point/comment/label': 'Review (optional).',
    'form/map_new_point/title/label': 'Title (optional).',
    'form/map_new_point/category/label': 'Category',
    'text/new_point/add_photos': 'Attach photo',
    'site/title/map/index': 'Landmarks on the world map',
    'site/title/catalog/index': 'The choice of the country.',
    'site/title/catalog/country': '%country%.',
    'site/title/catalog/state': '%country%. %state%.',
    'site/title/catalog/placemark': '%title%. %state%. %country%.',
    'site/title/catalog/placemark_no_states': '%title%. %country%.',
    'site/title/main/index': 'Landmarks on the world map',
    'site/title/catalog/search/title': 'Search',
    'site/title/catalog/search': 'Search',
    'site/title/catalog/search/submit/text': 'Search',
    'site/title/catalog/search/form/title/label': 'Keywords',
    'site/title/catalog/search/form/category/label': 'Category',
    'site/title/catalog/search/form/country/label': 'Country',
    'site/title/catalog/search/form/all_countries': 'Any country',
    'site/title/catalog/search/form/all_categories': 'Any category',
    'site/keywords/main/index': 'landmark, landmarks, attraction, attracions, world map',
    'site/keywords/catalog/index': '',
    'site/keywords/map/index': '',
    'site/keywords/catalog/search': '',
    'site/description/main/index': 'Review landmarks from around the world - created by human hands or by nature.',
    'site/description/catalog/index': '',
    'site/description/map/index': '',
    'site/description/catalog/search': '',
    'site/description/catalog/sitemap_countries/country': 'The list of landmarks. %country%.',
    'site/description/catalog/sitemap_countries/index': 'The list of landmarks. Select a country.',
    'site/description/catalog/sitemap_categories/category': 'The list of landmarks. %category%.',
    'site/description/catalog/sitemap_categories/index': 'The list of landmarks. Select a category.',
    'hat/logo/under_text': 'landmarks around the world',
    'page_bottom/column_1/header/text': 'Services',
    'page_bottom/catalog/text': 'Catalog',
    'page_bottom/map/text': 'Map',
    'page_bottom/search/text': 'Advanced search',
    'page_bottom/rights/text': '© World-Landmarks.ru - browse landmarks around  the world. All rights reserved. For all questions contact on email <a class="nowrap" href="mailto:info@world-landmarks.ru" target="_blank" rel="noopener">info@world-landmarks.ru</a>.',
    'main/description': `This site is dedicated to the review sites from around the world - as created by human hands or by nature. Daily website updated with new entries. To view them you can use the services map and directory.
During playback you can easily jump from the catalog to the map and back without losing the desired page.
Every object, whether on the map or in a directory that has a detailed description with photos, a list of the most "close" to it objects, and more.`,
    'main/map/description': '',
    'main/catalog/description': '',
    'main/map/title': 'map',
    'main/catalog/title': 'catalog',
    'main/search/title': 'search',
    'main/catalog/link': 'Go',
    'main/map/link': 'Go',
    'main/last_articles/text': 'Last articles',
    'main/last_placemarks/text': 'All placemarks',
    'catalog/country/last_articles/text': 'Last articles',
    'map/default_title_part/value': 'placemark:',
    'errors/new_point/category_none': 'Select a category',
    'category/info/title/text': 'Categories:'
}