import Consts from 'src/settings/Consts';


export default {
    'countries/undefined/name': 'Прочие места',
    'errors/new_point/photos_upload': 'Пожалуйста, приложите хотя бы одно фото.',
    'errors/new_point/photos_uploaded_yet': 'Фотографии еще загружаются.',
    'errors/new_point/photos_upload_more_than_available': 'Количество фотографий больше допустимого. Количество превышено на:',
    'errors/new_point/coords_empty': 'Пожалуйста, выберите место на карте.',
    'errors/new_point/another_actions': 'Сперва завершите добавление новой метки.',
    'errors/link_id_not_found': 'Метка с таким id не найдена на этой карте, возможно она удалена :(',
    'errors/search/empty_params': 'Пожалуйста, введите данные для поиска.',
    'errors/new_point/wrong_email': 'Неверно введен email',
    'errors/update_point/wrong_password': 'Пароль введен неверно, либо это не ваша запись.',
    'errors/update_point/empty_password': 'Нужно ввести пароль, который ранее был выслан вам на почту.',
    'text/new_point/loading': 'загрузка...',
    'errors/system': 'Системная ошибка! Пожалуйста обратитесь к администратору сайта.',
    'success/new_point/placemark_added': 'Метка добавлена, сейчас вы перейдете в раздел редактирования',
    'success/new_point/created': 'Запись успешно добавлена',
    'success/new_point/updated': 'Запись успешно обновлена',
    'success/new_article/created': 'Статья успешно добавлена',
    'success/article/updated': 'Статья успешно обновлена',
    'success/article/deleted': 'Статья успешно удалена',
    'success/point/deleted': 'Запись успешно удалена',
    'visitors/welcome/1/text': 'Благодарим Вас за посещение нашего сайта! <br>Надеемся, Вам у нас понравится :).',
    'visitors/interest/1/title/text': `<span style="color:#0070C3">Благодарим Вас за проявленный интерес!</span>`,
    'visitors/interest/1/description/text': "Если Вы не против, мы будем иногда присылать Вам письма с новыми интересными достопримечательностями. <br><br> <small>Если Вы пожелаете отказаться от наших писем, то всегда сможете нажать в письме на кнопку <b style=\"font-weight:bold;\">Мне это не интересно</b></small>.",
    'buttons/new_point/add': 'Добавить',
    'buttons/new_point/delete_photo': 'Удалить',
    'buttons/new_point/delete_placemark': 'Удалить метку',
    'buttons/new_point/update': 'Править',
    'buttons/new_point/existing_photos_title': 'Загруженные фото',
    'sweet_alert/delete_placemark/notation': 'Данные будут удалены безвозвратно',
    'buttons/new_point/close': 'Отмена',
    'sweet_alert/are_you_sure': 'Вы уверены?',
    'sweet_alert/new_point/close/notation': 'Ваши данные не будут сохранены.',
    'sweet_alert/redact_point/close/notation': 'Вы хотите отменить редактирование?',
    'sweet_alert/yes': 'Да',
    'sweet_alert/no': 'Нет',
    'buttons/placemark/viewer/hide': 'На карте',
    'buttons/placemark/viewer/show': 'Вернуться',
    'buttons/placemark/viewer/close': 'Закрыть',
    'buttons/new_point/place_at_map': 'Поменять место на карте',
    'buttons/new_point/return_to_editor': 'Перейти к редактированию',
    'buttons/new_point/cancel': 'Отмена',
    'buttons/new_point/commit': 'Сохранить',
    'notice/new_point/check_place': 'Укажите место на карте',
    'notice/load_placemarks/big_zoom': 'Ничего не загрузилось. Слишком большая площадь. Попробуйте приблизить масштаб.',
    'notice/map/filter/start/text': 'Идет фильтрация, пожалуйста подождите.',
    'notice/map/filter/reset/text': 'Идет сброс фильтра, пожалуйста подождите.',
    'warning/search/empty_result': 'Ничего не найдено.',
    'text/new_point/title': 'Добавить метку на карту',
    'text/new_point/title_update': 'Обновить запись',
    'map/panel_tools/where_am_i/title': '<br>где я нахожусь',
    'map/panel_tools/placemark_add_open/title': 'добавить<br>новую метку',
    'map/panel_tools/link/catalog': 'Каталог',
    'map/panel_tools/link/main': 'Главная страница',
    'map/placemark/link_to_catalog': 'Посмотреть в каталоге',
    'map/panel_tools/filter/category/title': 'Показать только:',
    'map/panel_tools/filter/category/selected/title': 'Выбрано:',
    'map/panel_tools/filter/title': '<br>фильтр',
    'panel_tools/settings/title': 'Настройки/Settings',
    'panel_tools/settings_back/title': 'Назад',
    'panel_tools/settings/head': 'Настройки',
    'panel_tools/settings/language/title': 'Язык сайта',
    'map/panel_tools/filter/head': 'Фильтр',
    'catalog/panel_tools/link/map': 'Карта',
    'map/panel_tools/filter_back/title': '<br>назад',
    'map/panel_tools/filter_reset/title': '<br>сброс фильтра',
    'catalog/panel_tools/link/filter': 'Поиск',
    'catalog/panel_tools/link/catalog': 'Каталог',
    'catalog/panel_tools/link/catalog/search': 'Поиск',
    'catalog/panel_tools/link/article': 'Статьи',
    'breadcrumbs/catalog/text': 'Каталог',
    'breadcrumbs/article/text': 'Статьи',
    'map/panel_tools/link/all_placemarks': 'Все метки',
    'map/panel_tools/link/filter': 'Поиск',
    'text/new_point/step_1': 'Описание места.',
    'text/general_review': 'Общий обзор',
    'form/map_generic_new_point/email/label': 'Ваш Email (не обязательно). Это даст вам возможность редактировать эту запись в будущем.',
    'form/map_generic_new_point/password/label': 'Введите пароль (он был ранее выслан вам на почту, если вы указали email).',
    'map/placemark/link/text': 'Ссылка на место: ',
    'catalog/placemark/link_to_map/text': 'Посмотреть на карте ',
    'map/placemark/adress/text': '', //Адрес места:
    'email/send_password_after_create_placemark/subject': 'Ваш пароль',
    'email/send_password_after_create_placemark/body': 'Пароль: <b>%password%</b><br>С помощью этого пароля вы сможете редактировать ваши записи на любой из карт проекта Instorage.',
    'email/send_password_after_create_placemark/alt_body': 'С помощью этого пароля вы сможете редактировать ваши записи на любой из карт проекта Instorage.',
    'catalog/index/header': 'Выберите страну',
    'catalog/country/back_link': 'Вернуться к выбору стран',
    'catalog/placemark/back_link_states': 'Другие метки в этом регионе',
    'catalog/placemark/back_link_countries': 'Другие метки в этой стране',
    'catalog/placemark/back_link_undefined': 'Другие метки',
    'catalog/country/photoalbum_title/text': 'Последние загруженные фото',
    'catalog/state/photoalbum_title/text': 'Последние загруженные фото',
    'catalog/state/back_link_states': 'Выбрать другой регион',
    'catalog/state/back_link_countries': 'Другие страны',
    'relevant_placemarks/title/text': 'Вам будет это интересно:',
    'another_placemarks/title/text': 'Другие объекты:',
    'another_articles/title/text': 'Другие статьи:',
    'placemarks_count/1/text': 'Всего меток: ',
    'placemarks_count/2/text': 'меток: ',
    'catalog/states/regions/list/title': 'Регионы',
    'sitemap_categories/header/text': 'Выберите категорию',
    'sitemap/empty_list/text': 'Список пуст',
    'sitemap_countries/header/text': 'Выберите страну',
    'upload_file_plugin/uploadstr/value': '',
    'upload_file_plugin/deletelStr/value': 'Отмена',
    'page_bottom/sitemap_countries/text': 'Поиск меток по странам',
    'page_bottom/sitemap_categories/text': 'Поиск меток по категориям',
    'page_bottom/articles_countries/text': 'Просмотр статей по странам',
    'page_bottom/articles_categories/text': 'Просмотр статей по категориям',
    'articles_countries/header/text': 'Выберите страну',
    'articles_categories/header/text': 'Выберите категорию',
    'site/title/catalog/sitemap_countries/country': 'Карта сайта. %country%.',
    'site/title/catalog/sitemap_countries/index': 'Карта сайта. Страны.',
    'site/title/catalog/sitemap_categories/category': 'Карта сайта. %category%.',
    'site/title/catalog/sitemap_categories/index': 'Карта сайта. Категории.',
    'site/keywords/catalog/sitemap_countries/index': 'страны',
    'site/keywords/catalog/sitemap_categories/index': 'категории',
    'text_form/tags/a/title': 'Ссылка',
    'text_form/tags/p/title': 'Абзац',
    'text_form/tags/b/title': 'Выделить жирным',
    'text_form/tags/strong/title': 'Тег <strong>',
    'text_form/tags/img/title': 'Изображение',
    'site/title/articles/country': 'Статьи о мировых достопримечательностях. %country%.',
    'site/title/articles/category': 'Статьи о мировых достопримечательностях. %category%.',
    'site/title/articles/index': 'Статьи о мировых достопримечательностях.',
    'site/description/articles/country': '', //'Статьи. %country%',
    'site/description/articles/category': '', //'Статьи. %country%',
    'site/description/articles/index': '', //'Статьи. Выберите страну',
    'site/keywords/articles/index': '',
    ['form/map_new_point/category/' + Consts.MY_NONE_CATEGORY_CODE]: 'Выберите из списка',
    'form/map_new_point/category/0': 'Прочие места',
    'form/map_new_point/category/1': 'Замки',
    'form/map_new_point/category/2': 'Дворцы, усадьбы',
    'form/map_new_point/category/3': 'Заброшенные здания',
    'form/map_new_point/category/4': 'Памятники архитектуры, исторические здания',
    'form/map_new_point/category/5': 'Архитектурные комплексы (кремли, монастыри)',
    'form/map_new_point/category/6': 'Храмы, церкви, соборы (христианство)',
    'form/map_new_point/category/7': 'Мечети',
    'form/map_new_point/category/8': 'Синагоги',
    'form/map_new_point/category/9': 'Музеи, выставочные залы',
    'form/map_new_point/category/10': 'Памятники и монументы',
    'form/map_new_point/category/11': 'Места культуры (театры, консерватории)',
    'form/map_new_point/category/12': 'Зоопарки, дельфинарии',
    'form/map_new_point/category/13': 'Цирки',
    'form/map_new_point/category/14': 'Индустриальные объекты',
    'form/map_new_point/category/15': 'Сады и парки',
    'form/map_new_point/category/16': 'Памятные места',
    'form/map_new_point/category/17': 'Необычные места',
    'form/map_new_point/category/18': 'Горы',
    'form/map_new_point/category/19': 'Вулканы',
    'form/map_new_point/category/20': 'Пещеры',
    'form/map_new_point/category/21': 'Водоемы',
    'form/map_new_point/category/22': 'Водопады',
    'form/map_new_point/category/23': 'Родники',
    'form/map_new_point/category/24': 'Памятники археологии, руины',
    'form/map_new_point/category/25': 'Фонтаны',
    'form/map_new_point/category/26': 'Крепости, укрепления',
    'form/map_new_point/category/27': 'Улицы, площади, бульвары',
    'form/map_new_point/category/28': 'Буддистские храмы',
    'form/map_new_point/category/29': 'Учебные заведения',
    'form/map_new_point/category/30': 'Библиотеки',
    'form/map_new_point/comment/label': 'Комментарий (не обязательно).',
    'form/map_new_point/title/label': 'Заголовок (не обязательно).',
    'form/map_new_point/category/label': 'Категория',
    'text/new_point/add_photos': 'Приложить фото',
    'site/title/map/index': 'Достопримечательности на карте мира',
    'site/title/catalog/index': 'Выбор страны.',
    'site/title/catalog/country': '%country%.',
    'site/title/catalog/state': '%country%. %state%.',
    'site/title/catalog/placemark': '%title%. %state%. %country%.',
    'site/title/catalog/placemark_no_states': '%title%. %country%.',
    'site/title/main/index': 'Достопримечательности на карте мира',
    'site/title/catalog/search/title': 'Поиск',
    'site/title/catalog/search': 'Поиск',
    'site/title/catalog/search/submit/text': 'Поиск',
    'site/title/catalog/search/form/title/label': 'Ключевое слово',
    'site/title/catalog/search/form/category/label': 'Категория',
    'site/title/catalog/search/form/country/label': 'Страна',
    'site/title/catalog/search/form/all_countries': 'Любая страна',
    'site/title/catalog/search/form/all_categories': 'Любая категория',
    'site/keywords/main/index': 'достопримечательности,достопримечательности на карте мира,карта мира',
    'site/keywords/catalog/index': '',
    'site/keywords/map/index': '',
    'site/keywords/catalog/search': '',
    'site/description/main/index': 'Обзор достопримечательностей со всего мира - как созданных руками человека, так и самой природой.',
    'site/description/catalog/index': '',
    'site/description/map/index': '',
    'site/description/catalog/search': '',
    'site/description/catalog/sitemap_countries/country': 'Список достопримечательностей. %country%.',
    'site/description/catalog/sitemap_countries/index': 'Список достопримечательностей. Выберите страну.',
    'site/description/catalog/sitemap_categories/category': 'Список достопримечательностей. %category%.',
    'site/description/catalog/sitemap_categories/index': 'Список достопримечательностей. Выберите категорию.',
    'hat/logo/under_text': 'достопримечательности мира',
    'page_bottom/column_1/header/text': 'Сервисы',
    'page_bottom/catalog/text': 'Каталог',
    'page_bottom/map/text': 'Карта',
    'page_bottom/search/text': 'Расширенный поиск',
    'page_bottom/rights/text': '© World-Landmarks.ru - достопримечательности мира. Все права защищены. По всем вопросам обращаться по адресу <a class="nowrap" href="mailto:info@world-landmarks.ru" target="_blank" rel="noopener">info@world-landmarks.ru</a>.',
    'main/description': `Данный сайт посвящен обзору достопримечательностей со всего мира - как созданных руками человека, так и самой природой.
        Ежедневно сайт пополняется новыми записями. Ознакомиться с ними вы можете с помощью сервисов - карты и каталога.
        Во время просмотра можно легко переходить с каталога на карту и обратно, не теряя нужной страницы.
        Каждый объект, будь он на карте или в каталоге, имеет подробное описание с фотографиями, список наиболее "близких" ему объектов и многое другое.`,
    'main/map/description': `Если вы отправились в путешествие, то это наиболее удобный способ познакомиться с местными достопримечательностями.
            Нажав на кнопку "определить мое местоположение", вы увидите объекты, которые находятся в непосредственной близости от вас, с подробным описанием каждого.`,
    'main/catalog/description': 'Позволяет быстро ознакомиться с достопримечательностями любой интересующей вас страны, выбрав её из списка.',
    'main/map/title': 'карта',
    'main/catalog/title': 'каталог',
    'main/search/title': 'поиск',
    'main/catalog/link': 'Перейти',
    'main/map/link': 'Перейти',
    'main/last_placemarks/text': 'Все метки',
    'main/last_articles/text': 'Новые статьи',
    'catalog/country/last_articles/text': 'Новые статьи',
    'map/default_title_part/value': 'метка:',
    'errors/new_point/category_none': 'Укажите категорию',
    'category/info/title/text': 'Категории:',
};